blog_website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func 

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True )
    email = db.Column(db.String(100), unique=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    posts = db.relationship('Post', backref='user', passive_deletes=True)
    comments = db.relationship('Comment', backref='user', passive_deletes=True)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    comments = db.relationship('Comment', backref='post', passive_deletes=True)

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(200), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    author = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id', ondelete='CASCADE'), nullable=False)

blog_website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager





db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "secretkey"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .models import User, Post, Comment

    with app.app_context():
        create_database()

    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
       return User.query.get(int(id))

    return app

def create_database():
    if not path.exists("blog_website/" + DB_NAME):
        db.create_all()
        print("Created database!")

blog_website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db 
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)



@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        user = User.query.filter_by(email=email).first()
        if user: 
            if check_password_hash(user.password, password):
                flash("Successfully logged in.", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("You entered the wrong password.", category='error')
        else: 
            flash("We could not find the email address you provided.", category='error')

    return render_template("login.html", user=current_user)

@auth.route("/sign-up", methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get("username")
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        if email_exists:
            flash('Hey! The email address already exists.', category='error')
        elif username_exists:
            flash('Hey! The username already exists.', category='error')
        elif password1 != password2:
            flash('Oh no, the passwords do not match.', category='error')
        elif len(username) < 3:
            flash('Oops, the username is too short.', category='error')
        elif len(password1) < 6:
            flash('Oops, make sure the password is a minimum of 6 characters.', category='error')
        elif len(email) < 4:
            flash('Hey! The email address is invalid.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()
            flash('User has been created!')
            return redirect(url_for('views.home'))
     

    return render_template("signup.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

blog_website/views.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User, Comment 
from . import db


views = Blueprint("views", __name__)


@views.route("/")
@views.route("/home")
@login_required
def home():
    posts = Post.query.all() 

    return render_template("home.html",  user=current_user, posts=posts)

@views.route("/post-blog", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        text = request.form.get('text')
        if not text:
            flash('Sorry, post cannot be blank.', category="error")
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Successfully posted a blog!', category="success")
            return redirect(url_for('views.home'))
            
    return render_template('createpost.html', user=current_user)

@views.route("/delete-blog/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('Permission denied. You cannot delete the post.', category="error")
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted', category='success')
    return redirect(url_for('views.home'))

@views.route("/posts/<username>")
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        flash('Sorry, user not found.', category='error')
        return redirect(url_for('views.home'))
 
    posts = user.posts
    return render_template("posts.html", user=current_user, posts=posts, username=username)


@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty.')
    else:
        post = Post.query.filter_by(id = post_id).first()
        if post:
            comment = Comment(text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been added!', category='success')
        else:
            flash('Cannot locate post.', category='error')
    return redirect(url_for('views.home'))

@views.route('/delete-comment/<comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('Permission denied.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))

blog_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="/home">Home</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="/logout">Log Out</a>
                    {% else %}
                    <a class="nav-item nav-link" href="/login">Log In</a>
                    <a class="nav-item nav-link" href="/sign-up">Sign Up</a>
                    {% endif %}
                </div>
                
            </div>
        </div>    
    </nav>
   
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == "error" %}
                    <div class="alert alert-danger alter-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                {% endif %}
            {% endfor%}
        {% endif %}
    {% endwith%}
    
   
    
    <div class="container">{% block content%}{% endblock %}</div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

</body>
</html>

blog_website/templates/createpost.html
{% extends "base.html" %}

{% block title%}Home{% endblock %}
{% block content%}
<br>
<br>
<a href="/home">
    <button type="button" class="btn btn-secondary">Go back to home page</button>
</a>    
<br>
<br>
<h1 align="center">Post a blog</h1>
<br>
<h3 align="center"><i>Speak your mind</i></h3>
<br>
<form action="{{ url_for('views.create_post') }}", method="POST">
    <textarea name="text" id="text" class="form-control"></textarea>
    <br>
    <br>
    <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
    </div>
</form>
{% endblock %}

blog_website/templates/home.html
{% extends "posts_div.html" %}

{% block title%}Home{% endblock %}

blog_website/templates/login.html
{% extends "base.html" %}

{% block title%}Login{% endblock %}
{% block content%}
<form method="POST">
    <br>
    <h3 align="center">Login</h3>
    <br>
    <br>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="please enter email">
 
        
        <br>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="please enter password">
        <br>
        <br>
        <div align="center">
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
        
    </div>
</form>
{% endblock %}

blog_website/templates/posts.html
{% extends "posts_div.html" %}

{% block title%}{{username}}'s blogs{% endblock %}
{% block  header%}

<div class="text-start">
    <a href="/home" >
        <button type="button" class="btn btn-secondary" align="">Go back to home page</button>
    </a>
</div>  
<br>
<br>
{{username}}'s blogs
{% endblock %}

{% block footer %}
{% endblock %}

blog_website/templates/posts_div.html
{% extends "base.html" %}

{% block title%}Home{% endblock %}
{% block content%}
<br>
<br>
<h3>blogBook</h3>
<br>
<h1 align="center">{% block header %}Blogs{% endblock %}</h1>
<br>
<h2>Your posts</h2>
<br>
<div id="posts" >
    {% for post in posts %}
    <div class="card border-dark mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <a href="/posts/{{post.user.username}}">{{post.user.username}}</a>
            {% if user.id == post.author %}
            <div class="btn-group">
                <button type="button" class="btn btn-sm btn-danger dropdown-toggle" data-bs-toggle="dropdown"></button>    
                <ul class="dropdown-menu">
                    <li><a href="/delete-blog/{{post.id}}" class="dropdown-item">Delete</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
        
<div class="card-body">
            <div class="card-text">{{post.text}}</div>
            <br>
            <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{post.id}}">
                        {% if post.comments %}
                            {% for comment in post.comments %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <a href="/post/{{comment.user.username}}">{{comment.user.username}}</a><span class="fst-italic">: {{comment.text}}</span>
                                </div>
                                <div class="d-flex align-items-center">
                                    <small class="text-muted">{{comment.date_created}}</small>
                                    {% if user.id == comment.author or user.id == post.author %}
                                    <div class="btn-group ms-2">
                                        <button type="button" class="btn btn-sm btn-danger dropdown-toggle" data-bs-toggle="dropdown"></button>    
                                        <ul class="dropdown-menu">
                                            <li><a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a></li>
                                        </ul>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <br>  
            <p class="card-text">
            {% if post.comments | length > 0 %}
                <a href="#comments-{{post.id}}" data-bs-toggle="collapse" role="button">
                    <small>View {{post.comments|length}} comments</small>
                </a>
            {% else %}
                <small class="text-muted">No comments to show</small>
            {% endif %}
            </p>
            <form class="input-group mb-3" action="create-comment/{{post.id}}" method="POST">
                <input type="text" name="text" class="form-control" placeholder="Say something here!">
                <button type="submit" class="btn btn-primary">Comment</button>
            </form> 
        </div>
        <div>
            <div class="bg-dark text-white p-1">{{post.date_created}}</div>
        </div>
    </div>
    {% endfor %}
    {% block footer %}
    <br>
    <div align="center">
        <a href="./post-blog">
            <button type="button" class="btn btn-primary btn-lg">Post a blog</button>
        </a>
    </div>
    <br>
    <br>
</div>

{% endblock %}
{% endblock %}

blog_website/templates/signup.html
{% extends "base.html" %}

{% block title%}Signup{% endblock %}
{% block content%}
<br> <br>
<h3>Join us today, sign up for free.</h3>
<br>
<br>
<form action="{{url_for('auth.signup')}}" method="POST">
    <label for="email">Email address</label>
    <input type="text" id="email" name="email" class="form-control" placeholder="please enter email">
    <br>
    <label for="username">Username</label>
    <input type="text" id="username" name="username" class="form-control" placeholder="please enter username">
    <br>
    <label for="password1">Password</label>
    <input type="password1" id="password1" name="password1" class="form-control" placeholder="please enter password">
    <br>
    <label for="password2">Re-enter password</label>
    <input type="password2" id="password2" name="password2" class="form-control" placeholder="please re-enter password">
    <br>
    <div align="center">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>
{% endblock %}